const genericNoteOptions: string[] = [
  'This is time-sensitive',
  'Flexible timeline',
  'Budget-conscious preferred',
  'Looking for long-term partnership',
  'One-time project',
  'Local provider preferred',
  'Remote service preferred',
  'Need detailed proposal first',
  'Previous positive experience',
  'New to this service',
  'High quality/premium service desired',
  'References would be helpful',

  'This treasure be time-sensitive, matey!',
  'Flexible timeline, whenever the wind blows right',
  'Seeking budget-friendly treasure, not breaking the bank',
  'Looking for a long-term crew partnership',
  'This be a one-time voyage',
  'Local port preferred, no long journeys',
  'Remote service works, can sail from afar',
  'Need a detailed map before we set sail',
  'Had smooth sailing with similar services before',
  'New to these waters, need a trustworthy guide',
  'Premium quality service desired, spare no expense',
  'References from other captains would be helpful',
  'All hands on deck - urgent mission!',
  'Seeking the finest treasure in the seven seas',
  'Need someone who knows these treacherous waters',
  'Looking for a crew member who speaks plain English',
  'This bounty may lead to more adventures',
  'Discretion required - keep this treasure secret',
  'Fair winds and following seas timeline',
  'Seeking a seasoned navigator for this quest',
  'Small treasure hunt, quick and simple',
  'Major expedition requiring experienced crew'
]

export default genericNoteOptions
